### ISSUE TITLE
cannot see the result

### ISSUE THREAD

**Issue by akausas** [ColCarroll/strava_calendar#3]
I cannot obtain plot data from both my machines: one on Mac and another is Ubuntu.
Can it be the issue that my activities name are different from the code pattern:
`pattern = re.compile(r"^activities/\d+.fit.gz$")`

my files have name similar to this:  _2047704054.gpx_

**Comment by ColCarroll** [comment]
Sorry for closing 3 years later, but I think this is fixed now! Hope you're doing well.
