### ISSUE TITLE
Some years of plot_calendar() not working

### ISSUE THREAD

**Issue by benjackman** [ColCarroll/strava_calendar#5]
Hi Colin

First of all, thanks very much for this great tool and the very quick addition of .gpx support. It's been a pleasure to use.

I've noticed a strange bug with the latest version with .gpx support; Plot_calendar() appears to not be working for my 2019 or 2020 activities, but does work for earlier years. However, the get_data() to plot by month example **does** work for months in 2019.

Plot_calendar still works for 2017 and 2018, so it's not a general issue with that function.

All the activities are stored as .gpx files, and all the .gpx files appear present (of course, as otherwise the monthly plot for 2019 wouldn't work).

I've included a few screenshots below. These are all from the same notebook. 

Grateful for any thoughts you might have. Apologies if it's a simple mistake on my end!

![2019_not_working](https://user-images.githubusercontent.com/53864135/103471343-6867bf80-4dd3-11eb-9c8a-0d29bddab0b7.PNG)

![2019_months_working](https://user-images.githubusercontent.com/53864135/103471317-fdb68400-4dd2-11eb-8e64-2e3aaf4e2f15.PNG)

![2017_18_working](https://user-images.githubusercontent.com/53864135/103471346-6d2c7380-4dd3-11eb-83c6-d8707519c20b.PNG)

**Comment by ColCarroll** [comment]
A year late, but I found out this was from some _wild_ date handling code I had. It should be fixed now! 

I don't actually see the same behavior in your plots -- it used to be that a few days in January would be plotted at a coordinate like (0, 105123), while everything else would have a y-value that was less than 52. This caused the aspect ratio to become weird, and the whole plot would look wrong. 

January 1 would not trigger this (the code was _really wild_) but if January 2nd/3rd/4th were on a certain day of the week, there'd be trouble.

Closing this a year late after pushing some changes, but feel free to reopen (I ran on my 2022 data successfully yesterday). Hope it has been a good year!
